### ISSUE TITLE
add new function based on df

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#24]
see #23 , will invite @aedobbyn to the repo.

We can 

* discuss here&on Slack and

* work on implementation in a devel branch

**Comment by maelle** [comment]
@aedobbyn I'll take some notes here, maybe a bit messy, sorry.

First of all thanks so much for your PR! Good for users and I see you caught at least one error 🙀 

I like the name actually! It's clear, one sees what it does.

I wonder whether we should add the same for extract. If we do this smartly maybe it wouldn't be too much work to write the two at the same time?

If we can avoid adding `dplyr` as a dependency then good. Well and `tidyr` depends on `dplyr` :joy: But like you I tend to use these functions so we'll see!

The "pkg::fun" syntax is enough, no need to add imports via importFrom on top of that, see http://r-pkgs.had.co.nz/namespace.html "It’s common for packages to be listed in Imports in DESCRIPTION, but not in NAMESPACE. In fact, this is what I recommend: list the package in DESCRIPTION so that it’s installed, then always refer to it explicitly with pkg::fun(). Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future." That said I didn't follow this at the time I wrote the code so I'll need to delete my _own_ call to importFrom ahahah.

We could also update the vignette.

When we're done in dev we shall not forget to add you as "aut" to DESCRIPTION and to add an entry in NEWS.md explaining what was added and that it was added by you.

**Comment by aedobbyn** [comment]
@maelle thanks for these notes! I had a lot of these on my list of to-dos so that's perfect :smile: This is the list I've got so far -- let me know if I missed some things:

- add `monkeylearn_extract_df()`
- update the vignette with an example of `monkeylearn_classify_df()` of `monkeylearn_extract_df()`
- try to bind rows with `rbind()` rather than `dplyr::bind_rows()` to avoid the dplyr dependency
- try to unnest rows without `tidyr::unnest()`

I also had on the list a to-do to implement the md-5 hash that's used in both the main result and the headers of `monkeylearn_classify()` and `monkeylearn_extract()`. As you mentioned earlier, it doesn't seem strictly necessary for the `_df()` functions so I wonder whether it's better to leave it out for simplicity's sake or include it for consistency .

Something I was curious about regarding `monkeylearn_classify()` was why queries are split into (hardcoded) groups of 20 when we define `request` in line 49. I let the user change this in #23  but kept the default `texts_per_req` to 20. However, I think 200 is the max recommended query length, so do you see a downside in setting the default query length to 200?

Another question: I noticed that there is no `params` argument in `monkeylearn_classify()` and though it's included in the call to `monkeylearn_prep()` in line 61, it's set to `NULL`. I was wondering why that was -- is it something specific to the default classifier or to all classification modules? If so, I'll dig into the differences between extractors and classifiers before writing `monkeylearn_extract_df()`.

Thanks for the tip re: not explicitly adding `importFrom`s! I'm going to go read that post one more time. Do you want to take the task of editing those to conform to the style you think is best?
Re: the name, I think the `_df` suffix to the function is fine but it doesn't message that the function allows for distinct 1:1 mappings between each individual input text and its classification. Hmmm. Maybe just something that we need to rely on documentation to message.

**Comment by maelle** [comment]
Nice list! 

> Something I was curious about regarding monkeylearn_classify() was why queries are split into (hardcoded) groups of 20 when we define request in line 49. I let the user change this in #23 but kept the default texts_per_req to 20. However, I think 200 is the max recommended query length, so do you see a downside in setting the default query length to 200?

I don't remember details exactly but I thought it was 200? Maybe it changed? 

> Another question: I noticed that there is no params argument in monkeylearn_classify() and though it's included in the call to monkeylearn_prep() in line 61, it's set to NULL. I was wondering why that was -- is it something specific to the default classifier or to all classification modules? If so, I'll dig into the differences between extractors and classifiers before writing monkeylearn_extract_df().

Again a very good question and I don't remember why I wrote that :scream:

Yes I can edit the functions to remove importFrom.

Could you close your PR (if your rights allow that, I _think_ so) and create a dev or devel branch in this repo where we can both work? Thank you!

**Comment by maelle** [comment]
I forgot to say that yes md5 is useless if the function outputs a data.frame. Your function makes the df experience much user-friendlier. 😁

**Comment by maelle** [comment]
Don't close your PR cf #28

**Comment by aedobbyn** [comment]
Okay! I'll add an issue for adding the option to set `params` in all of the functions. I mentioned in #28 -- I've kept the `classify-df` branch around because it's got a new function `classify_vec()` and changes to `classify_df()` to accept a `vec` as input. These are redundant so I think we should pick one. I'd lean towards having two separate functions for piping's sake; in the `classify-df` branch implementation of `classify_df()` you can't pipe in a vector argument. Definitely can be persuaded, though!

**Comment by maelle** [comment]
What about having only the df function, and if the input is a character vector it would transform it to a df with a warning?

And the current classify function already takes a vector as input.

**Comment by aedobbyn** [comment]
Ah I like that! So the first argument we'd rename to `input` or something, and if `input` is a dataframe then the second argument, `col` would have to be supplied. Otherwise, `input` is a vector and we can follow the behavior of `monkeylearn_classify_vec()`. I think that might be the best way to preserve pipeability and simplicity 😊

Right, the difference between `monkeylearn_classify()` and `monkeylearn_classify_vec()` is that the latter returns a nested (or unnested if specified) dataframe similar to `classify_df()`which retains the relationship between each text and its classification(s). I think looping that functionality into `monkeylearn_classify_df()` as discussed above will let us remove `monkeylearn_classify_vec()`. And, the `_df` suffix can refer to the output being a dataframe rather than the input, since we'd now accept both vectors and dataframes as inputs. What do you think?

**Comment by maelle** [comment]
I think it's great!

Maybe to make it clearer the name could be `monkeylearn_classify_to_df` but it's getting too long 🤔   so happy to let it as it is!

The docs should have examples of piping to show how useful this is.

**Comment by maelle** [comment]
mmmh you know I actually think the behavior of the new function you're creating should be the one of that old function, had I been smarter. 

so maybe we should slowly deprecate the old one and call the new one `monkey_classify`? And it'd output either a nested or non nested data.frame based on an argument?

In `opencage` where a similar transformation is happening the old functions will be deprecated and the new ones are `oc_` instead of `opencage_`.

**Comment by aedobbyn** [comment]
Yep, that sounds good! Do you think we should call the new version `ml_classify()` so we don't break people's code that uses the original `monkeylearn_classify()`?

If you want to go with the `ml_` prefix, I'm fine with either the `ml_classify_df()`and `ml_classify_vec()` combo or the ability of `ml_classify()` to take either a dataframe or a vector that we discussed above.

**Comment by maelle** [comment]
yes that or as I proposed, `monkey_classify` because `ml` sounds like machine learning. 😃

**Comment by aedobbyn** [comment]
I guess we'd also need to check whether `ml_classify` is already a name taken by another package... 😆

**Comment by maelle** [comment]
also `monkey` is fun 😹

**Comment by aedobbyn** [comment]
Oh my brain read `monkey_classify` that as `monkeylearn_classify`! Haha yes, I like `monkey_classify` a lot!

**Comment by maelle** [comment]
cool, then let's call it this way! 🐒 📁

**Comment by aedobbyn** [comment]
Ahahaha I love it. I'm sort of leaning toward distinguishing `monkey_classify_df()` and `monkey_classify_vec()` just to be explicit and so that people won't have to suppress warnings if they're only ever classifying vectors. But I'll follow your lead on this 😊

**Comment by maelle** [comment]
or we could transform it into a data.frame without a warning? So input can be two things? Not sure if it's best practice, but it doesn't sound too wrong?

**Comment by aedobbyn** [comment]
Sounds good to me! If it's untenable we can always break it up into two functions later, I suppose.

**Comment by aedobbyn** [comment]
I suppose we can close this guy now, yeah?

**Comment by maelle** [comment]
Yep!
