### ISSUE TITLE
Insert plug for other rOpenSci packages that need some love into blog post

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#88]
Space left open with `# Insert plug for other rOpenSci packages that need some love` :)

**Comment by aedobbyn** [comment]
Link to blog post .Rmd: https://github.com/aedobbyn/roweb2/blob/dev/content/blog/2018-03-22-monkeydo.Rmd

**Comment by aedobbyn** [comment]
After some answers here https://discuss.ropensci.org/t/best-blog-post-writing-practices-re-image-file-paths-and-footnotes/1112/5 it doesn't seem like there's a totally seamless workflow here so what I've been doing is writing in the .Rmd where image paths are commented out (since it won't knit to .md with image paths of `/img/blog-images/2018-03-22-monkeydo/`, you'd need to append `../../themes/ropensci/static/` to the beginning of that) and then uncommenting out the image paths on the .md to be able to `hugo serve` the site locally.

For whatever reason `knitr::opts_knit$set(root.dir = normalizePath("../../themes/ropensci/static"))` didn't solve the working directory problem. Not sure why. 

Like I said, I've just been working straight off of dev, but feel free to make a new branch if you'd like --
 you should have push access 😊

**Comment by maelle** [comment]
mmmh makes me think I should add a function to help create blog posts to my very much only a list of ideas package for rOpenSci package authors! 

I'll add my blurb here because of that 🙈  @sckott this is a blurb for the end of Amanda's post, where she explained how she became a contributor to `monkeylearn`. The goal of the blurb is to encourage more people to do that.

"You too can become a contributor to an rOpenSci package! Have a look at the issues tracker of your favorite rOpenSci package(s) e.g. [`rgbif`](https://github.com/ropensci/rgbif/issues). Browse issues suitable for beginners over many rOpenSci repos thanks to [Lucy D'Agostino McGowan's `contributr` Shiny app](https://ropensci.shinyapps.io/contributr/). Always first ask in a new or existing issue whether your contribution would be welcome, plan a bit with the maintainer, and then have fun! We'd be happy to have you."

**Comment by aedobbyn** [comment]
@maelle I *love* this idea!

**Comment by aedobbyn** [comment]
Got it, thanks @maelle!
